### ISSUE TITLE
1.5.2 Patch is Invalid

### ISSUE THREAD

**Issue by robfrawley** [nginx-modules/ngx_http_extended_status_module#6]
I don't actually have a solution for fixing extended_status-1.5.2.patch - I just realized it was incomplete during my rewrite of this module @ https://github.com/scribenet/nginx-servats-module.

I was implementing Travis CI tests for my rewrite early-on and realized that the `1.5.2` patch, while it can be successfully applied to the relevant Nginx source, doesn't actually apply everything needed for Nginx to  successfully compile. This applies to both my re-write of this module, as well as this module itself.

The line length of the [1.5.2 patch of 543 lines](https://github.com/nginx-modules/ngx_http_extended_status_module/blob/master/patches/extended_status-1.5.2.patch#L543) compared to the patches for both `1.4.2` and `1.6.2` which both have line lengths of about 780 lines is a dead give-away.

**Comment by robfrawley** [comment]
For the time being I have removed it from my module: https://github.com/scribenet/nginx-servats-module. If anyone has an accurate patch file for `1.5.2` or wants to go through it and figure what is missing, it would be beneficial to both projects! Thanks!

**Comment by denji** [comment]
Я добавил вас к @nginx-modules/nginx-upstream-statistics

Maybe you will be interested, thank you.
